# Generated by Django 4.0.5 on 2022-08-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='national_code',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userbase',
            name='short_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
